CREATE DATABASE books;

CREATE TABLE book(book_id SERIAL PRIMARY KEY,title VARCHAR(255),description VARCHAR(255));

CREATE DATABASE users;

CREATE TABLE user(userid SERIAL PRIMARY KEY,name VARCHAR(255),email VARCHAR(255),password VARCHAR(255) );